# Generated by Django 4.1 on 2022-09-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_account_bio_account_image_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='phone', verbose_name='phone'),
        ),
    ]
